### ISSUE TITLE
How to install this library with poetry?

### ISSUE THREAD

**Issue by slidenerd** [PrithivirajDamodaran/Parrot#43]
Does this library support installation via poetry?

**Comment by pedrojlazevedo** [comment]
Hey!

I added like this :)

```toml
[tool.poetry.dependencies]
fuzzywuzzy = "^0.18.0"
parrot = { git = "https://github.com/PrithivirajDamodaran/Parrot_Paraphraser.git", branch = "main" }
```
